#!/usr/bin/exec-suid -- /usr/local/bin/python -I

import pathlib

config = (pathlib.Path(__file__).parent / ".config").read_text().strip()

print(f"Instance: {config}")

with open("/flag") as f:
    print(f.read())
