#!/usr/bin/exec-suid -- /usr/local/bin/python -I

import pathlib
import random

with open("/flag") as f:
    random.seed(f.read())

planets = (pathlib.Path(__file__).parent / "planets.txt").read_text().strip().splitlines()

print("This is a flag-seeded random number: {}".format(random.randint(0, 1000)))
print(random.choice(planets))

with open("/flag") as f:
    print(f.read())
